Sprint 1.task 3.3
Taipei-yp/taipei-runner pull request #59
Opened 2020-12-27 18:00 UTC by rdnsr

2020-12-28 14:22 UTC, DmitryKhitrin commented on client/components/text/text.tsx
> +  header = false,
isHeader

2020-12-28 14:25 UTC, DmitryKhitrin commented on client/pages/error/error.tsx
> +        <Text header text={textTop} size="extra3" color="accent" />
Кажется тут должен быть контейнер, внутри которого уже лежат блоки text.

2020-12-28 14:27 UTC, DmitryKhitrin commented on client/components/page/page.tsx
> +const Page: FC<Props> = ({
Идея постройки универсального контейнера подо все, кажется не очень удобной. Ведь если нужно поменять что-то только на одной странице, придется постоянно задумываться а как бы не разломать остальные. В данном случае копипаста некоторого количества css оправдана удобством.

2020-12-28 14:58 UTC, kyponomarev requested changes
Эти изменения вызывают ошибку. Если пофиксить ошибку из-за которой падает, то страницы ошибок выглядят совсем не как на макете. Возможно потребуются доп классы стили для .app  Предлагаю пофиксить это и потом снова посмотреть.

2020-12-28 14:58 UTC, kyponomarev commented on client/components/page/page.css
> +  flex-direction: column;
Надо добавить еще   `align-items: stretch;` чтобы элементы растягивались по всей ширине блока

2020-12-28 14:58 UTC, kyponomarev commented on client/components/page/page.css
> +  &__item_stretch {
Не совсем понял зачем нужен класс item? Почему нельзя все разместить child комопонент в блок с классом child?

2020-12-28 14:58 UTC, kyponomarev commented on client/components/page/page.tsx
> +  stretch?: boolean;
Мне кажется этот параметр не нужен (ну или я не понимаю для чего он нужен, особенно если мы откажемся от item'а)

2020-12-28 14:58 UTC, kyponomarev commented on client/components/text/text.css
> +  &_size_extra {
по названию этого модификатора непонятно большой это элемент или нет  (слово extra не несет инфы об этом). Ниже предложения по неймингу

2020-12-28 14:58 UTC, kyponomarev commented on client/styles/variables.css
>    --tpr-fontsize-button: 24px;
Вот этот размер удалим `-tpr-fontsize-button: 24px;` тк он выбивается из сетки. А кнопку я переделаю

2020-12-28 14:58 UTC, kyponomarev commented on client/styles/variables.css
> +  --tpr-fontsize-x3: 96px;
Предлагаю добавить ко всем x еще и l, чтобы было понятно что это eXtra Large. А не eXtra Small т.е
--tpr-fontsize-xl
и вместо цифр давайте юзать буквы
т.е. --tpr-fontsize-2x будет --tpr-fontsize-xxl

В итоге:
--tpr-fontsize-sm: 16px;
 --tpr-fontsize: 18px;
  --tpr-fontsize-lg: 28px;
  --tpr-fontsize-xl: 36px;
  --tpr-fontsize-xxl: 64px;
  --tpr-fontsize-xxxl: 96px;

2020-12-28 14:58 UTC, kyponomarev commented on client/components/text/text.tsx
> +  header?: boolean;
Предлагаю выпилить это и юзать там где нужно компонент заголовка вместо компонента текста

2020-12-28 14:58 UTC, kyponomarev commented on client/components/text/text.tsx
> +  size?: "small" | "large" | "extra" | "extra2" | "extra3";
Предлагаю следующие модификаторы:
sm | lg | xl | xxl | xxxl

2020-12-28 15:24 UTC, rdnsr commented on client/components/page/page.css
> +  flex-direction: column;
align-items растягивает по вертикали, для того что бы растянулся по ширине добавлен класс &__item_stretch

2020-12-29 07:06 UTC, DmitryKhitrin approved these changes

2020-12-29 07:37 UTC, kyponomarev commented on client/components/page/page.tsx
> +const Page: FC<Props> = ({
@DmitryKhitrin Если такая необходимость будет, распилим универсальный контейнер позже..

2020-12-29 07:39 UTC, kyponomarev approved these changes
👍

2020-12-29 08:25 UTC, merged